In [2]:
import numpy as np

In [11]:
arr_1d = np.array([1,2,3,4,4])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 4]
[[1 2 3]
 [4 5 6]]


### List vs Array


In [12]:
py_list=[1,2,3]
print("Multiply with 2:", py_list*2)
arr_2d = np.array([[1,2,3],[4,5,6]])
# element wise multiplicatin
print("Multiply array by 2:", arr_2d*2) 

Multiply with 2: [1, 2, 3, 1, 2, 3]
Multiply array by 2: [[ 2  4  6]
 [ 8 10 12]]


### Notes on NumPy Array Creation Functions

- **np.zeros(shape)**  
  Creates an array of the given shape filled with zeros.  
  Example:  
  ```python
  np.zeros((2, 3))
  # Output:
  # [[0. 0. 0.]
  #  [0. 0. 0.]]
  ```

- **np.ones(shape)**  
  Creates an array of the given shape filled with ones.  
  Example:  
  ```python
  np.ones((3, 3))
  # Output:
  # [[1. 1. 1.]
  #  [1. 1. 1.]
  #  [1. 1. 1.]]
  ```

- **np.full(shape, value)**  
  Creates an array of the given shape filled with the specified value.  
  Example:  
  ```python
  np.full((4, 4), 10)
  # Output:
  # [[10 10 10 10]
  #  [10 10 10 10]
  #  [10 10 10 10]
  #  [10 10 10 10]]
  ```

- **np.arange(start, stop, step)**  
  Creates an array with regularly incrementing values from `start` to `stop` (exclusive), with a given `step`.  
  Example:  
  ```python
  np.arange(1, 11, 2)
  # Output:
  # [1 3
  

In [21]:
zeros = np.zeros((2,3))         # Creates a 2x3 array filled with zeros
print(zeros)

ones = np.ones((3,3))           # Creates a 3x3 array filled with ones
print(ones)

constant = np.full((4,4), 10)   # Creates a 4x4 array filled with the constant value 10
print(constant)

sequence = np.arange(1, 11, 2)  # Creates an array with values from 1 to 10 (step 2): [1, 3, 5, 7, 9]
print(sequence)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[1 3 5 7 9]


### Notes on NumPy Random Array Creation

- **np.random.random(shape)**  
  Creates an array of the given shape filled with random float values between 0.0 and 1.0.

  **Example:**
  ```python
  random = np.random.random((3, 3))
  print(random)
  # Output (example):
  # [[0.374 0.950 0.732]
  #  [0.598 0.156 0.156]
  #  [0.058 0.866

In [23]:
random =np.random.random((3,3))
print(random)

[[0.14704616 0.7213185  0.20570808]
 [0.27289173 0.2279368  0.33528551]
 [0.90804738 0.51261245 0.08703703]]


## Notes on Vector, Matrix, and Tensor in NumPy

- **Vector:**  
  A one-dimensional array.
  ```python
  Vector = np.array([1, 2, 3, 4])
  print(Vector)
  # Output:
  # [1 2 3 4]
  ```

- **Matrix:**  
  A two-dimensional array (rows and columns).
  ```python
  matrix = np.array([[1, 2, 3], [4, 5, 6]])
  print(matrix)
  # Output:
  # [[1 2 3]
  #  [4 5 6]]
  ```

- **Tensor:**  
  An array with three or more dimensions.
  ```python
  tensor = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])
  print(tensor)
  # Output:
  # [[[ 1  2  3]
  #   [ 4  5  6]]
  #
  #  [[ 7  8  9]
  #   [10 11

In [26]:
Vector = np.array([1,2,3,4])
print(Vector)

matrix =np.array([[1,2,3],[4,5,6,]])
print(matrix)

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print(tensor)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Notes on NumPy Array Properties

- **shape**: Returns a tuple representing the dimensions of the array (rows, columns, ...).
- **ndim**: Returns the number of dimensions (axes) of the array.
- **size**: Returns the total number of elements in the array.
- **dtype**: Returns the data type of the array elements.


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print('Shape',arr.shape)
print('Dimention',arr.ndim)
print('Size',arr.size)
print('Data Type:',arr.dtype)
array = np.identity(3, dtype = int)
print(array)


Shape (2, 3)
Dimention 2
Size 6
Data Type: int64
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Notes on NumPy Array Reshaping and Manipulation

- **reshape(new_shape)**: Changes the shape of the array without changing its data.
- **flatten()**: Returns a copy of the array collapsed into one dimension.
- **ravel()**: Returns a flattened array, but returns a view whenever possible.
- **T**: Transposes the array (swaps rows and columns for 2D arrays).


In [33]:
arr = np.array([1,2,3,4,5,6])
print("Original Array:", arr)

reshaped = arr.reshape((2,3))
print("Reshaped array:",reshaped)

flattened = arr.flatten()
print("Flattened Array:", flattened)

raveled = arr.ravel()
print("Ravel Array:", raveled)

transpose = reshaped.T
print(transpose)

Original Array: [1 2 3 4 5 6]
Reshaped array: [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Ravel Array: [1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
