In [1]:
import numpy as np

## Notes on NumPy Array Operations: Slicing and Indexing

- **Basic Slicing:**  
  You can extract a portion of an array using the syntax `arr[start:stop]`.  
  Example:
  ```python
  arr = np.array([1,2,3,4,5,6,7,8,9,10])
  print("Basic Slicing", arr[2:7])  # Output: [3 4 5 6 7]
  ```

- **Slicing with Step:**  
  You can specify a step value using `arr[start:stop:step]`.  
  Example:
  ```python
  print("with step:", arr[2:9:2])   # Output: [3 5 7 9]
  ```

- **Negative Indexing:**  
  Negative indices count from the end of the array.  
  Example:
  ```python
  print("negative indexing:", arr[-2])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("with step:",arr[2:9:2])
print("negarive indexing:", arr[-2])

## Notes on 2D NumPy Array Indexing and Slicing

- **Accessing a specific element:**  
  Use `arr_2d[row, column]` to access an element at a specific row and column.
  ```python
  arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
  print(arr_2d)
  print("2d indexing:", arr_2d[1,2])  # Output: 6
  ```

- **Accessing an entire row:**  
  Use `arr_2d[row]` to get all elements of a specific row.
  ```python
  print("entire row:", arr_2d[1])     # Output: [4 5 6]
  ```

- **Accessing an entire column:**  
  Use `arr_2d[:, column]` to get all elements of a specific column.
  ```python
  print("Entire column:", arr_2d[:,2])  # Output: [3 6

In [18]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print("2d indexing:", arr_2d[1,2])
print("entire row:", arr_2d[1])
print("Entire column:",arr_2d[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2d indexing: 6
entire row: [4 5 6]
Entire column: [3 6 9]


## Notes on NumPy Array Sorting

- **Sorting a 1D array:**  
  Use `np.sort(array)` to return a sorted copy of the array.
  ```python
  unsorted = np.array([1,4,1,3,5,6,1,2,3])
  print(unsorted)
  print("sorted array", np.sort(unsorted))  # Output: [1 1 1 2 3 3 4 5 6]
  ```

- **Sorting a 2D array:**  
  - By default, `np.sort(array_2d)` sorts each row.
  - Use `axis=0` to sort by columns.
  - Use `axis=1` to sort by rows.
  ```python
  arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
  print(arr_2d_unsorted)
  print("Sorted 2d array by column:", np.sort(arr_2d_unsorted, axis=0))
  # Output:
  # [[1 1]
  #  [2 2]
  #  [3 3]]

  print("Sorted by row:", np.sort(arr_2d_unsorted, axis=1))
  # Output:
  # [[1 3]
  #  [1 2]
  #  [2

In [39]:
unsorted = np.array([1,4,1,3,5,6,1,2,3])
print(unsorted)
print("sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(arr_2d_unsorted)
print("Sorted 2d array by column:", np.sort(arr_2d_unsorted, axis=0))
print("Sorted by row:", np.sort(arr_2d_unsorted, axis=1))

[1 4 1 3 5 6 1 2 3]
sorted array [1 1 1 2 3 3 4 5 6]
[[3 1]
 [1 2]
 [2 3]]
Sorted 2d array by column: [[1 1]
 [2 2]
 [3 3]]
Sorted by row: [[1 3]
 [1 2]
 [2 3]]


## Notes on NumPy Array Filtering

- **Filtering with Boolean Indexing:**  
  You can filter elements in a NumPy array using boolean conditions.

  **Example:**
  ```python
  numbers = np.array([1,2,3,4,5,6,7,8,9,10])
  print(numbers)

  # Get even numbers
  even = numbers[numbers % 2 == 0]
  print(even)  # Output: [ 2  4  6  8 10]

  # Filter by mask (numbers greater than 5)
  mask = numbers > 5
  print("Numbers greater than 5:", numbers[mask])  # Output: [ 6  7  8  9 10]

In [43]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
print(numbers)
even = numbers[numbers%2 == 0]
print(even)
# filter by mask
mask = numbers > 5
print("Numbers greater than 5:",numbers[mask])

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
Numbers greater than 5: [ 6  7  8  9 10]


## Notes on Fancy Indexing and `where` Keyword in NumPy

- **Fancy Indexing:**  
  You can use a list or array of indices to access multiple elements at once.
  ```python
  numbers = np.array([1,2,3,4,5,6,7,8,9,10])
  index = [1, 3, 5]
  print(numbers[index])  # Output: [2 4 6]
  ```

- **np.where(condition):**  
  Returns the indices where the condition is True. You can use these indices to filter or select elements.
  ```python
  where_result = np.where(numbers > 5)
  print(where_result)           # Output: (array([5, 6, 7, 8, 9]),)
  print(numbers[where_result])  # Output: [ 6  7  8  9 10]
  ```

In [49]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
index = [1,3,5]
print(numbers[index])
where_result = np.where(numbers > 5)
print(where_result)
print(numbers[where_result])

[2 4 6]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


## Notes on np.where with Condition

- **np.where(condition, x, y):**  
  Returns elements chosen from `x` or `y` depending on the condition. If the condition is True, the value from `x` is used; otherwise, the value from `y` is used.

  **Example:**
  ```python
  numbers = np.array([1,2,3,4,5,6,7,8,9,10])
  condition_arr = np.where(numbers > 5, numbers*4, numbers/2)
  print(condition_arr)
  # Output: [ 0.5  1.   1.5  2.   2.5 24.  28.  32.  36.  40. ]

In [52]:
condition_arr = np.where(numbers > 5, numbers*4, numbers/2)
print(condition_arr)

condition = np.where(numbers < 5, 'true', 'false')
print(condition)

[ 0.5  1.   1.5  2.   2.5 24.  28.  32.  36.  40. ]
['true' 'true' 'true' 'true' 'false' 'false' 'false' 'false' 'false'
 'false']


## Notes on Adding and Removing Data in NumPy Arrays

- **Concatenating Arrays:**  
  You can combine two or more arrays using `np.concatenate`.

  **Example:**
  ```python
  arr1 = np.array([1, 2, 3])
  arr2 = np.array([4, 5, 6])
  combined = np.concatenate((arr1, arr2))
  print(combined)  # Output: [1 2 3 4 5 6]
  ```

- **Deleting an element:**  
  Use `np.delete(array, index)` to remove an element at a specific index.

  **Example:**
  ```python
  deleted = np.delete(combined, 2)
  print(deleted)  # Output: [1 2 4

In [76]:
arr1 =np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

deleted = np.delete(combined, 2)
print("Array after deletion", deleted)

[1 2 3 4 5 6]
Array after deletion [1 2 4 5 6]


## Array Compatibility

- To check if two arrays are compatible (i.e., have the same shape), compare their `.shape` attributes.

**Example:**
```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
check = arr1.shape == arr2.shape
print("Check compatibility:", check)  # Output: Check compatibility: True
```
If `check` is `True`, the arrays have the same shape and can be combined or operated on element-wise.

In [57]:
check = arr1.shape == arr2.shape
print("Check compatibility:" ,check)

Check compatibility: True


## Notes on Adding Rows and Columns to NumPy Arrays

- **Adding a new row:**  
  Use `np.vstack()` to stack arrays in sequence vertically (row-wise).
  ```python
  original = np.array([[1,2],[3,4]])
  new_row = np.array([[6,7]])
  add_row = np.vstack((original, new_row))
  print("After adding row:\n", add_row)
  # Output:
  # [[1 2]
  #  [3 4]
  #  [6 7]]
  ```

- **Adding a new column:**  
  Use `np.hstack()` to stack arrays in sequence horizontally (column-wise).
  ```python
  new_col = np.array([[3], [6], [9]])
  add_col = np.hstack((add_row, new_col))
  print("After adding col:\n", add_col)
  # Output:
  # [[1 2 3]
  #  [3 4 6]
  #  [6 7 9]]
  ```

In [73]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[6,7]])

print("original:", original)
add_row = np.vstack((original, new_row))
print("After adding row:\n", add_row)

new_col = np.array([[3], [6], [9]])
add_col = np.hstack((add_row, new_col))
print("After adding col:\n", add_col)

original: [[1 2]
 [3 4]]
After adding row:
 [[1 2]
 [3 4]
 [6 7]]
After adding col:
 [[1 2 3]
 [3 4 6]
 [6 7 9]]
